language: node_js
node_js:
  - 0.10
  - 0.12
  - iojs
  - 4
  - 5
  - 6
script:
  - npm run eslint
notifications:
  slack:
    secure: uukBvDIxfpHgFbKRrNWD7BSLp4nI3Bdfjt+cDCpK5oXjx2cvw+x9v+AxZ+ZhMHloOvqhEjH3f9XdfLur7mPdFeHedOOoDsiwPkG3DXIJ1EWByJKjfl6zU2tIFHNWXjjdBIBfPw4PSOB0XYdbbIquJl4o5bdghyo9bhDQmHfGot84y8sHxifBz31jdCMOhP9mMARQaim31PU5ZhiQGfP+AajFWzl6x5Zr9mf4m3cu673DxSMPr/9fEKMAK0Z2q9I63R/QL/yvSi67d3JRhDVWeQ5hi9E/mLfebT0NHlpJtpQRhzbP4HhlSEME3AyhbH0WaqKDRzi4nCvy1cGB+X2lv31lagbjQu4OA05WbkmJo/LT8aCA7HAwvMlfgqIRCILTSTnie0lDXjRVwBDrDx8qn1njy7MXYgE42a3LumpWZrIPlVXwrWkG/uCyEgnEFrb9D8dNQ/2B0uHbb/KjdQRGRcGZDIIvDDP3nNE02d4/WheX0JU9R7onSAR2lw3k96/5LKGMKzh5y6KSa+zNe0Xs+FAXMTs8PE+G/kk3joU2Ev39qWB4N4YAKafwgSc51lzmK5str2yQDXIp1j204QU7BCX1QMmraklsXPmPeeD2Mjt8SiNv6rYNLRuHjR9BILRNw8dQT5yR6z+1aV0cfQBjc+qtTEm6U4vZpBo6dn7rRJk=
